import type { LucideIcon } from "lucide-react";
import {
  AreaChart,
  ArrowLeftRight,
  BarChart2,
  BarChart3,
  BarChart4,
  BarChartHorizontal,
  CalendarClock,
  CandlestickChart,
  Circle,
  CircleDot,
  Cloud,
  Combine,
  Crosshair,
  Droplets,
  Filter,
  Flower2,
  Gauge,
  GitBranch,
  Grid3x3,
  LayoutGrid,
  LayoutPanelTop,
  Layers,
  LineChart,
  Loader,
  Map as MapIcon,
  Box,
  Network,
  Percent,
  PieChart,
  Radar,
  ScatterChart,
  Sheet,
  Sparkles,
  Table2,
  Target,
  TrendingUp,
} from "lucide-react";
import { getChartPlugin } from "@/components/charts/engine/plugins/registry";

/** 各 chartType 独立图标（对标 DataEase Picker 一型一图标） */
export const CHART_TYPE_ICONS: Record<string, LucideIcon> = {
  gauge: Gauge,
  liquid: Droplets,
  kpi: TrendingUp,
  table: Table2,
  "table-info": Table2,
  "table-normal": Sheet,
  "table-pivot": LayoutPanelTop,
  "t-heatmap": Grid3x3,
  line: LineChart,
  area: AreaChart,
  "area-stack": Layers,
  timeline: CalendarClock,
  bar: BarChart3,
  "bar-stack": BarChart4,
  "percentage-bar-stack": Percent,
  "bar-group": BarChart2,
  "bar-group-stack": BarChart4,
  waterfall: Filter,
  "bar-horizontal": BarChartHorizontal,
  "bar-stack-horizontal": BarChartHorizontal,
  "percentage-bar-stack-horizontal": Percent,
  "bar-range": ArrowLeftRight,
  "bidirectional-bar": ArrowLeftRight,
  "progress-bar": Loader,
  "stock-line": CandlestickChart,
  "bullet-graph": Target,
  pie: PieChart,
  "pie-donut": CircleDot,
  "pie-rose": Flower2,
  "pie-donut-rose": CircleDot,
  radar: Radar,
  treemap: LayoutGrid,
  "word-cloud": Cloud,
  wordCloud: Cloud,
  map: MapIcon,
  "map-3d": Box,
  heatmap: Grid3x3,
  scatter: ScatterChart,
  quadrant: Crosshair,
  funnel: Filter,
  sankey: GitBranch,
  "circle-packing": Circle,
  "multi-scatter": Sparkles,
  graph: Network,
  combo: Combine,
  "chart-mix": Combine,
  "chart-mix-group": Combine,
  "chart-mix-stack": Layers,
  "chart-mix-dual-line": LineChart,
};

const PALETTE_CATEGORY_ICONS: Record<string, LucideIcon> = {
  quota: Gauge,
  table: Table2,
  trend: LineChart,
  compare: BarChart3,
  distribute: PieChart,
  map: MapIcon,
  relation: Network,
  dual_axes: Combine,
};

export function chartTypeIcon(type: string): LucideIcon {
  const direct = CHART_TYPE_ICONS[type];
  if (direct) return direct;
  const category = getChartPlugin(type)?.paletteCategory;
  if (category && PALETTE_CATEGORY_ICONS[category]) {
    return PALETTE_CATEGORY_ICONS[category];
  }
  return LineChart;
}
