export const ds03Mock = {
  cityGauges: [
    { label: "城市安全指数", value: 94.6, unit: "分" },
    { label: "交通畅通率", value: 87.2, unit: "%" },
    { label: "环境达标率", value: 91.8, unit: "%" },
    { label: "公共服务满意度", value: 89.4, unit: "%" },
  ],
  industryStructure: [
    { rank: 1, label: "数字经济", value: 92 },
    { rank: 2, label: "先进制造", value: 84 },
    { rank: 3, label: "现代服务", value: 78 },
    { rank: 4, label: "绿色能源", value: 71 },
    { rank: 5, label: "文旅消费", value: 63 },
  ],
  departmentWords: [
    { text: "城管", weight: 95 },
    { text: "交通", weight: 88 },
    { text: "环保", weight: 82 },
    { text: "应急", weight: 76 },
    { text: "公安", weight: 90 },
    { text: "水务", weight: 68 },
    { text: "住建", weight: 74 },
    { text: "市场监管", weight: 62 },
    { text: "卫健", weight: 58 },
    { text: "消防", weight: 85 },
  ],
  globeNodes: [
    { id: "bj", label: "北京", lon: 116, lat: 40, status: "normal" as const, detail: "首都圈 · 综合运行指数 96.2，交通指数良好" },
    { id: "sh", label: "上海", lon: 121, lat: 31, status: "normal" as const, detail: "长三角枢纽 · 港口物流畅通，PM2.5 达标" },
    { id: "gz", label: "广州", lon: 113, lat: 23, status: "warning" as const, detail: "华南门户 · 暴雨预警，内涝风险点 3 处待排查" },
    { id: "cd", label: "成都", lon: 104, lat: 30, status: "normal" as const, detail: "西部中心 · 轨道交通准点率 99.1%" },
    { id: "wh", label: "武汉", lon: 114, lat: 30, status: "alert" as const, detail: "长江中游 · 江段水位超警，已启动防汛 IV 级响应" },
    { id: "xa", label: "西安", lon: 109, lat: 34, status: "normal" as const, detail: "西北节点 · 古城保护巡查正常" },
  ],
  alertRows: [
    { id: "a1", time: "14:32", location: "滨江大道", content: "占道施工未报备，影响晚高峰通行", status: "warning" as const },
    { id: "a2", time: "14:18", location: "高新区", content: "PM2.5 短时升高，已派巡检车复核", status: "info" as const },
    { id: "a3", time: "13:56", location: "地铁 2 号线", content: "站台客流超限，已增派疏导人员", status: "critical" as const },
    { id: "a4", time: "13:41", location: "南湖片区", content: "消防通道占用已清理完毕", status: "resolved" as const },
    { id: "a5", time: "13:22", location: "政务中心", content: "窗口排队时长超 15 分钟预警", status: "warning" as const },
    { id: "a6", time: "12:58", location: "长江大桥", content: "桥面风速监测正常，无限行", status: "info" as const },
  ],
  issueRows: [
    { seq: "1", type: "市容秩序", location: "解放路步行街", unit: "城管局", foundAt: "2026-06-28 09:12", status: "整改中", progress: "60%" },
    { seq: "2", type: "交通拥堵", location: "二环高架东段", unit: "交警支队", foundAt: "2026-06-28 08:45", status: "已派单", progress: "30%" },
    { seq: "3", type: "噪声扰民", location: "学府小区北侧", unit: "生态环境局", foundAt: "2026-06-27 22:18", status: "待复核", progress: "80%" },
    { seq: "4", type: "积水内涝", location: "站前广场地下通道", unit: "水务集团", foundAt: "2026-06-27 16:30", status: "整改中", progress: "45%" },
    { seq: "5", type: "设施损坏", location: "市民公园照明", unit: "市政养护", foundAt: "2026-06-27 11:05", status: "已完成", progress: "100%" },
    { seq: "6", type: "食品安全", location: "农贸市场的 3 号档口", unit: "市场监管局", foundAt: "2026-06-26 15:40", status: "已闭环", progress: "100%" },
  ],
} as const;

export const {
  cityGauges: ds03CityGauges,
  industryStructure: ds03IndustryStructure,
  departmentWords: ds03DepartmentWords,
  globeNodes: ds03GlobeNodes,
  alertRows: ds03AlertRows,
  issueRows: ds03IssueRows,
} = ds03Mock;
