from __future__ import annotations

# NFR 横切
NFR_PLUGIN_EXTENSION_UNAVAILABLE = "NFR_PLUGIN_EXTENSION_UNAVAILABLE"

# NFR-006 推送
PUSH_CONFIG_INVALID = "PUSH_CONFIG_INVALID"

# NFR-006 推送通道 companion
PUSH_CHANNEL_DEGRADED = "PUSH_CHANNEL_DEGRADED"
PUSH_CHANNEL_ALL_FAILED = "PUSH_CHANNEL_ALL_FAILED"

# NFR 横切 probe 超时（非阻塞）
NFR_PROBE_TIMEOUT = "NFR_PROBE_TIMEOUT"

# NFR-007 信创
XINCHUANG_NON_COMPLIANT = "XINCHUANG_NON_COMPLIANT"

# NFR-008 零 DE/SS 运行时
NFR_RUNTIME_VIOLATION = "NFR_RUNTIME_VIOLATION"

# NFR-002 报表查询性能 probe
REPORT_PERF_REPORT_REQUIRED = "REPORT_PERF_REPORT_REQUIRED"
REPORT_PERF_BUDGET_OUT_OF_RANGE = "REPORT_PERF_BUDGET_OUT_OF_RANGE"
REPORT_PERF_SAMPLE_OUT_OF_RANGE = "REPORT_PERF_SAMPLE_OUT_OF_RANGE"
REPORT_PERF_FORBIDDEN = "REPORT_PERF_FORBIDDEN"
REPORT_PERF_INVALID_SAMPLE_QUERY = "REPORT_PERF_INVALID_SAMPLE_QUERY"

# NFR-003 核心看板可用性 SLA
DASHBOARD_SLA_DASHBOARD_REQUIRED = "DASHBOARD_SLA_DASHBOARD_REQUIRED"
DASHBOARD_SLA_WINDOW_OUT_OF_RANGE = "DASHBOARD_SLA_WINDOW_OUT_OF_RANGE"
DASHBOARD_SLA_BELOW_TARGET = "DASHBOARD_SLA_BELOW_TARGET"
DASHBOARD_SLA_FORBIDDEN = "DASHBOARD_SLA_FORBIDDEN"
DASHBOARD_SLA_INVALID_DASHBOARD_ID = "DASHBOARD_SLA_INVALID_DASHBOARD_ID"
DASHBOARD_SLA_ALERT_THRESHOLD_OUT_OF_RANGE = "DASHBOARD_SLA_ALERT_THRESHOLD_OUT_OF_RANGE"

# NFR-001 Dashboard 首屏性能
DASHBOARD_FIRST_SCREEN_DASHBOARD_REQUIRED = "DASHBOARD_FIRST_SCREEN_DASHBOARD_REQUIRED"
DASHBOARD_FIRST_SCREEN_BUDGET_OUT_OF_RANGE = "DASHBOARD_FIRST_SCREEN_BUDGET_OUT_OF_RANGE"
DASHBOARD_FIRST_SCREEN_WIDGET_OUT_OF_RANGE = "DASHBOARD_FIRST_SCREEN_WIDGET_OUT_OF_RANGE"
DASHBOARD_FIRST_SCREEN_FORBIDDEN = "DASHBOARD_FIRST_SCREEN_FORBIDDEN"
DASHBOARD_FIRST_SCREEN_INVALID_DASHBOARD_ID = "DASHBOARD_FIRST_SCREEN_INVALID_DASHBOARD_ID"

# NFR-004 HTTPS 脱敏审计
HTTPS_AUDIT_INSECURE_URL = "HTTPS_AUDIT_INSECURE_URL"
HTTPS_AUDIT_EMPTY_PAYLOAD = "HTTPS_AUDIT_EMPTY_PAYLOAD"
HTTPS_AUDIT_UNKNOWN_FIELD = "HTTPS_AUDIT_UNKNOWN_FIELD"
HTTPS_AUDIT_FORBIDDEN = "HTTPS_AUDIT_FORBIDDEN"
HTTPS_AUDIT_INVALID_SCOPE = "HTTPS_AUDIT_INVALID_SCOPE"

# GOV-005 发布（errors 常量集中出口，publish/errors.py re-export）
GOV_PUBLISH_ENTRY_NOT_FOUND = "GOV_PUBLISH_ENTRY_NOT_FOUND"
GOV_PUBLISH_INVALID_TRANSITION = "GOV_PUBLISH_INVALID_TRANSITION"
GOV_PUBLISH_ALREADY_PENDING = "GOV_PUBLISH_ALREADY_PENDING"
GOV_PUBLISH_FORBIDDEN = "GOV_PUBLISH_FORBIDDEN"
